// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sql} from '../models';

export function Exist(arg1:sql.DB,arg2:sql.Tx):Promise<boolean>;

export function Save(arg1:sql.DB,arg2:sql.Tx):Promise<void>;
