// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exist(arg1, arg2) {
  return window['go']['db']['Dir']['Exist'](arg1, arg2);
}

export function Save(arg1, arg2) {
  return window['go']['db']['Dir']['Save'](arg1, arg2);
}
