// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ProcessDirectory() {
  return window['go']['main']['App']['ProcessDirectory']();
}

export function ReadProcessedDirs() {
  return window['go']['main']['App']['ReadProcessedDirs']();
}
