// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function ProcessDirectory():Promise<void>;

export function ReadProcessedDirs():Promise<Array<db.Dir>>;
